/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb.vue')['default']
    CaseTable: typeof import('./../src/components/caseTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormHdButton: typeof import('./../src/components/form/hd-button.vue')['default']
    FormHdError: typeof import('./../src/components/form/hd-error.vue')['default']
    FormHdInput: typeof import('./../src/components/form/hd-input.vue')['default']
    FormHdLink: typeof import('./../src/components/form/hd-link.vue')['default']
    GlobalBanner: typeof import('./../src/components/global/banner.vue')['default']
    GlobalButton: typeof import('./../src/components/global/button.vue')['default']
    GlobalExportButton: typeof import('./../src/components/global/exportButton.vue')['default']
    GlobalHeaderNotAccount: typeof import('./../src/components/global/headerNotAccount.vue')['default']
    GlobalInputOrSelect: typeof import('./../src/components/global/inputOrSelect.vue')['default']
    GlobalOperateButton: typeof import('./../src/components/global/operateButton.vue')['default']
    GlobalSaveButton: typeof import('./../src/components/global/saveButton.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditorEditor: typeof import('./../src/components/wangEditor/editor.vue')['default']
  }
}
